name: Build Go Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        architecture: [ amd64, arm64 ]
        os: [ linux, darwin ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'  # Specify the Go version you want to use

      - name: Build Go binary
        run: |
          GOARCH=${{ matrix.architecture }} GOOS=${{ matrix.os }} go build -ldflags "-s -w" -o gupdate-${{ matrix.os }}-${{ matrix.architecture }}

      - name: Upload binary
        uses: softprops/action-gh-release@v2
        with:
          files: gupdate-${{ matrix.os }}-${{ matrix.architecture }}
          tag_name: v1.0.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
